CREATE TYPE status_order as enum('created','processing','delivered');

CREATE TABLE product(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(200) NOT NULL,
    description varchar(5000),
    price money NOT NULL
);

CREATE TABLE "order"(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_of_creation timestamp,
    status status_order NOT NULL DEFAULT('created')
);

CREATE TABLE product_order(
    order_id int REFERENCES "order"(id),
    product_id int REFERENCES product(id),
    quantity int NOT NULL DEFAULT (1)
);
